steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/pso-pubsec-demos/demos/Helloworld:$SHORT_SHA', '.' ]
images:
- 'us-central1-docker.pkg.dev/pso-pubsec-demos/demos/Helloworld:$SHORT_SHA'