steps:

 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   id: Deploy UAT 
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'helloworld'
   - '--image'
   - 'us-central1-docker.pkg.dev/$PROJECT_ID/demos/helloworld:$SHORT_SHA'
   - '--region'
   - 'us-east4'